export const tutorialCards = [
  {
    title: "Theme and authorization",
    text: "On the main page, in the upper right corner, you can change the theme and go to the authorization page.",
    imageSrc: "/images/tutorial/tutorial1.png",
    width: 500,
    height: 500,
  },
  {
    title: "Sign Up",
    text: "To register, you only need to provide your name, username, and password. The application is completely anonymous, so you can use any name you want. It's all up to you!",
    imageSrc: "/images/tutorial/tutorial2.png",
    width: 500,
    height: 500,
  },
  {
    title: "Sign In",
    text: "User authorization is no worse than registration. All you need to remember is your username and password, and you can easily access the application!",
    imageSrc: "/images/tutorial/tutorial3.png",
    width: 500,
    height: 500,
  },
  {
    title: "Chat",
    text: "It's a place where you can communicate with your friends or meet other people, but you can remain anonymous. And our minimalist design will make your communication even more enjoyable!",
    imageSrc: "/images/tutorial/tutorial4.png",
    width: 700,
    height: 700,
  },
  {
    title: "Sidebar",
    text: "A great way to navigate, thanks to it you will never get lost in our application, because everything is simple, just click on one of the elements, and it will open the page you need.",
    imageSrc: "/images/tutorial/tutorial5.png",
    width: 400,
    height: 400,
  },
  {
    title: "User Search",
    text: "You can find the people you need quickly and securely by simply entering their name or username",
    imageSrc: "/images/tutorial/tutorial6.png",
    width: 500,
    height: 500,
  },
  {
    title: "Messaging",
    text: "Our chat is secure, messages are encrypted in a unique way, because we use our own technology for this, so no one can access your messages.",
    imageSrc: "/images/tutorial/tutorial7.png",
    width: 500,
    height: 500,
  },
  {
    title: "Group Creation",
    text: "Creating groups? It's easy! With our app, you can quickly gather a group of friends for more effective communication. It's more fun together!",
    imageSrc: "/images/tutorial/tutorial8.png",
    width: 500,
    height: 500,
  },
  {
    title: "Group Management",
    text: "Of course, we did not forget to make it possible to manage the group. Of course, there will be a leader in the group, but he or she will be able to give rights to someone else.  In addition, the leader will be able to edit the created group and clean it up if necessary. Or everyone can do it for themselves. As you like!",
    imageSrc: "/images/tutorial/tutorial9.png",
    width: 500,
    height: 500,
  },
];
