server:
  port: 9090
  id: 'E1'
  instances:
    value: 'E2'
    separator: ','

spring:
  application:
    name: ws-server

  data:
    redis:
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'

logging:
  level:
    com.chat.wsserver: INFO