export { default as FormOutlineIcon } from "./form-outline.svg";
export { default as LockOutlineIcon } from "./lock-outline.svg";
export { default as PinOutlineIcon } from "./pin-outline.svg";
export { default as SettingOutlineIcon } from "./setting-outline.svg";
export { default as SignOutCircleIcon } from "./sign-out-circle.svg";
export { default as UserFillIcon } from "./user-fill.svg";
export { default as UserOutlineIcon } from "./user-outline.svg";
export { default as UserPlusOutlineIcon } from "./user-plus-outline.svg";
export { default as CurvedArrowIcon } from "./сurved-arrow-icon.svg";
