export const MESSAGE_CONTAINER = {
  DEFAULT_MESSAGE_CONTAINER_HEIGHT: "auto",
  SHOW_SCROLL_DOWN_BUTTON_THRESHOLD_HEIGHT: -500,
};

export const MESSAGE_INPUT = {
  MAX_TEXTAREA_HEIGHT: 250,
  DEFAULT_TEXTAREA_HEIGHT: "auto",
};
