spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lw-chat
    username: root
    password: 123

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
