spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lw-chat
    username: root
    password: 123

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

jwt:
  subject: 'link-wave-security'
  issuer: 'link-wave-issuer'
  secret-key:
    refresh: 'dGzVEWkq1FoqTMCQnCMrHvnZJYl1x4QG'
    access: '1RY76H1VEP37eMCyYI24wvgmMkhtOgUH'
  exp:
    refresh: 30
    access: 60


files:
  avatar:
    path: 'C:\Users\Igor\Desktop\images'
    default: '1.jpg'