server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'

spring:
  application:
    name: 'chat-service'

  servlet:
    multipart:
      max-file-size: 32MB
      max-request-size: 32MB

  data:
    mongodb:
      host: 'localhost'
      port: 27017
      database: 'linkwave'
      replica-set-name: 'rs0'

files:
  storage-folder: 'D:\Files\storage'

logging:
  level:
    org.linkwave.chatservice: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
