import * as Icons from "@public/icons";

export const DEFAULT_ICON_SIZE = 24;

export const iconMapping = {
  "chat-outline": Icons.ChatPlusOutlineIcon,
  "form-outline": Icons.FormOutlineIcon,
  "group-outline": Icons.GroupOutlineIcon,
  "lock-outline": Icons.LockOutlineIcon,
  "pin-outline": Icons.PinOutlineIcon,
  "setting-outline": Icons.SettingOutlineIcon,
  "sign-out-circle": Icons.SignOutCircleIcon,
  "user-fill": Icons.UserFillIcon,
  "user-outline": Icons.UserOutlineIcon,
  "user-plus-outline": Icons.UserPlusOutlineIcon,
  "curved-arrow": Icons.CurvedArrowIcon,
  "time-outline": Icons.TimeOutlineIcon,
  "link-outline": Icons.LinkOutlineIcon,
  "list-outline": Icons.ListOutlineIcon,
  "left-angle": Icons.LeftAngleIcon,
  "pen-with-message": Icons.PenWithMessageIcon,
  "remove-circle-outline": Icons.RemoveCircleOutlineIcon,
  "add-chat-outline": Icons.AddChatOutlineIcon,
  "find-contacts-outline": Icons.FindContactsOutlineIcon,
  "add-circle-outline": Icons.AddCircleOutlineIcon,
  "folder-outline": Icons.FolderOutlineIcon,
  "send-outline": Icons.SendOutlineIcon,
  "angle-down": Icons.AngleDownIcon,
  "chat-plus-outline": Icons.ChatPlusOutlineIcon,
  "line-horizontal": Icons.LineHorizontalIcon,
  "clock-outline": Icons.TimeOutlineIcon,
  "broken-link-outline": Icons.BrokenLinkOutlineIcon,
  "close-outline": Icons.CloseOutlineIcon,
  "edit-outline": Icons.EditOutlineIcon,
  "trash-bucket-outline": Icons.TrashBucketOutlineIcon,
  "exit-outline": Icons.ExitOutlineIcon,
  "users-outline": Icons.UsersOutlineIcon,
  "crown-outline": Icons.CrownOutlineIcon,
  "minus-circle-outline": Icons.MinusCircleOutline,
};
